using AtsrolPOSAPI.Domain.Common;
using Microsoft.AspNetCore.Identity;

namespace AtsrolPOSAPI.Domain.Entities.Identity
{
    public class AppUser : IdentityUser
    {
        // Extra profile fields based on ERD and additional context
        public string? EmpNo { get; set; } // e.g., EMP-001 generated by NoSeries
        public string? Name { get; set; }
        public string? NationalID { get; set; }

        // Company and Store relationships for multi-tenancy

        public string CompanyId { get; set; } = default!;
        public string? StoreOfOperationId { get; set; }


        public bool IsActive { get; set; } = true;
        public DateTimeOffset? LastLoginAt { get; set; }
        public int LoginCount { get; set; }
        public string? LastLoginIP { get; set; }
        public string? Role { get; set; }

        // Password management

        public bool PasswordChangeRequired { get; set; }

        // Soft delete flag
        public bool IsDeleted { get; set; }

        // Navigation properties

        public Core.Company? Company { get; set; }
        public Core.Store? StoreOfOperation { get; set; }


        /// <summary>
        /// Many-to-many: All stores assigned to this user
        /// </summary>
        public ICollection<UserStore> UserStores { get; set; } = new List<UserStore>();
    }
}
